version: 1
default_environment: dev
project_id: 0198cf5e-5994-79cf-b139-fa589862c550
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-mysql
    variant: transferwise
    pip_url: 
      git+https://github.com/transferwise/pipelinewise.git#subdirectory=singer-connectors/tap-mysql
    config:
      host: bec-db-rds.cvii44gkul2j.ap-southeast-1.rds.amazonaws.com
      database: bec-db-rds      
      user: admin
      password: $TAP_MYSQL_PASSWORD
      port: 3306
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 104857600
      credentials_path: $GOOGLE_CLOUD_CREDENTIALS_JSON
      dataset: $TARGET_BIGQUERY_DATASET
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: $TARGET_BIGQUERY_PROJECT

# Jobs configuration
jobs:
- name: rds-to-bigquery
  tasks:
  - tap-mysql target-bigquery
  
# Hooks for automated cleanup
hooks:
  post-invoke:
    tap-mysql:
      - python meltano-post-hook.py
    target-bigquery:
      - python meltano-post-hook.py
  post-run:
    rds-to-bigquery:
      - python meltano-post-hook.py

